name: CI-latihan

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

env:
  CSV_URL: "train_pca.csv"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      # Set Git config ONCE at the start (no need to repeat)
      - name: Configure Git
        run: |
          git config --global user.name "${{ secrets.username }}"
          git config --global user.email "${{ secrets.email }}"

      - name: Set up Python 3.12.7
        uses: actions/setup-python@v4
        with:
          python-version: "3.12.7"
      
      - name: Check Env
        run: echo $CSV_URL
 
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install mlflow
      
      - name: Run mlflow project
        run: mlflow run . --env-manager=local 

      - name: Install google dependencies
        run: |
          pip install --upgrade google-auth google-auth-oauthlib google-auth-httplib2 google-api-python-client
        
      - name: Upload to Google Drive
        env:
          GDRIVE_CREDENTIALS: ${{ secrets.GDRIVE_CREDENTIALS }}  # Mengambil kredensial dari GitHub Secrets
          GDRIVE_FOLDER_ID: ${{ secrets.GDRIVE_FOLDER_ID }}  # Mengambil kredensial dari GitHub Secrets
        run: |
          python upload_to_gdrive.py

      # Git LFS setup (no need for repeated Git config)
      - name: Set up Git LFS
        run: |
          git lfs install
          git lfs track "mlruns/**"
          git add .gitattributes
          git commit -m "Track large files in mlruns with Git LFS" || true
          git push origin main
         
      # Save models (no need for repeated Git config)
      - name: Save mlruns to repo
        run: |
          git add -f mlruns/
          git commit -m "Save mlruns from CI run" || true
          git push origin main
